@echo off
REM ###########################################################################
REM Script generated by HP Fortify SCA Scan Wizard (c) HP Fortify 2011
REM Created on 2012/11/06 10:07:07
REM ###########################################################################
REM Generated for the following languages:
REM 	Java
REM 	XML
REM ###########################################################################
REM DEBUG - if set to true, runs SCA in debug mode
REM SOURCEANALYZER - the name of the SCA executable
REM BUILDID - the SCA build id
REM LAUNCHERSWITCHES - the launcher settings that are used to invoke SCA
REM ARGFILE - the name of the argument file that's extracted and passed to SCA
REM MEMORY - the memory settings for SCA
REM CLIENT - the name of the fortifyclient executable
REM SSCURL - the SSC url for uploading the FPR
REM SSCPROJECT - the name of the project to upload the FPR to
REM SSCVERSION - the name of the project version to upload the FPR to
REM SSCTOKEN - the token for authenticating the FPR upload
REM OLDFILENUMBER - this defines the file which contains the number of files within the project, it is automatically generated
REM FILENOMAXDIFF - this is the percentage of difference between the number of files which will trigger a warning by the script
REM ###########################################################################

set DEBUG=false
set SOURCEANALYZER=sourceanalyzer
set FPR="FortifyConfApp.fpr"
set SSCURL=http://127.0.0.1:8180/ssc
set SSCPROJECT="ConfApp"
set SSCVERSION="1.0"
set SSCTOKEN=41cf3780-aae0-4c7e-b7a1-8d6a69168375
set CLIENT=fortifyclient
set BUILDID="ConfApp"
set ARGFILE="FortifyConfApp.bat.args"
set MEMORY=-Xmx2800M -Xms600M -64 -Xss24M 
set LAUNCHERSWITCHES=""
set OLDFILENUMBER=FortifyConfApp.bat.fileno
set FILENOMAXDIFF=10

set PROJECTROOT1="C:\Users\565075\android-sdks"
set PROJECTROOT0="C:\projects\secure mobile\sample apps\ConfApp"
IF NOT EXIST %PROJECTROOT1% (
   ECHO  ERROR: This script is being run on a different machine than it was
   ECHO         generated on or the targeted project has been moved. This script is 
   ECHO         configured to locate files at
   ECHO            %PROJECTROOT1%
   ECHO         Please modify the %%PROJECTROOT1%% variable found
   ECHO         at the top of this script to point to the corresponding directory
   ECHO         located on this machine.
   GOTO :FINISHED
)
IF NOT EXIST %PROJECTROOT0% (
   ECHO  ERROR: This script is being run on a different machine than it was
   ECHO         generated on or the targeted project has been moved. This script is 
   ECHO         configured to locate files at
   ECHO            %PROJECTROOT0%
   ECHO         Please modify the %%PROJECTROOT0%% variable found
   ECHO         at the top of this script to point to the corresponding directory
   ECHO         located on this machine.
   GOTO :FINISHED
)

IF %DEBUG%==true set LAUNCHERSWITCHES=-debug %LAUNCHERSWITCHES%
echo Extracting Arguments File


echo. >FortifyConfApp.bat.args
SETLOCAL ENABLEDELAYEDEXPANSION
IF EXIST %0 (
   set SCAScriptFile=%0
) ELSE (
  set SCAScriptFile=%0.bat
)

set PROJECTROOT1=%PROJECTROOT1:)=^)%
set PROJECTROOT0=%PROJECTROOT0:)=^)%
FOR /f "delims=" %%a IN ('findstr /B /C:"REM ARGS" %SCAScriptFile%' ) DO (
   set argVal=%%a
   set argVal=!argVal:PROJECTROOT1_MARKER=%PROJECTROOT1:~1,-1%!
   set argVal=!argVal:PROJECTROOT0_MARKER=%PROJECTROOT0:~1,-1%!
   echo !argVal:~9! >> %ARGFILE%
)
ENDLOCAL

REM ###########################################################################
echo Cleaning previous scan artifacts
%SOURCEANALYZER% %MEMORY% %LAUNCHERSWITCHES% -b %BUILDID% -clean 
IF %ERRORLEVEL%==1 (
echo Sourceanalyzer failed, exiting
GOTO :FINISHED
)
REM ###########################################################################
echo Translating files
%SOURCEANALYZER% %MEMORY% %LAUNCHERSWITCHES% -b %BUILDID% @%ARGFILE%
IF %ERRORLEVEL%==1 (
echo Sourceanalyzer failed, exiting
GOTO :FINISHED
)
REM ###########################################################################
echo Testing Difference between Translations
SETLOCAL
FOR /F "delims=" %%A in ('%SOURCEANALYZER% -b %BUILDID% -show-files ^| findstr /R /N "^" ^| find /C ":" ') DO SET FILENUMBER=%%A
IF NOT EXIST %OLDFILENUMBER% (
	ECHO It appears to be the first time running this script, setting %OLDFILENUMBER% to %FILENUMBER%
	ECHO %FILENUMBER% > %OLDFILENUMBER%
	GOTO TESTENDED
)

FOR /F "delims=" %%i IN (%OLDFILENUMBER%) DO SET OLDFILENO=%%i
set /a DIFF=%OLDFILENO% * %FILENOMAXDIFF%
set /a DIFF /=  100
set /a MAX=%OLDFILENO% + %DIFF%
set /a MIN=%OLDFILENO% - %DIFF%

IF %FILENUMBER% LSS %MIN% set SHOWWARNING=true
IF %FILENUMBER% GTR %MAX% set SHOWWARNING=true

IF DEFINED SHOWWARNING (
	ECHO WARNING: The number of files has changed by over %FILENOMAXDIFF%%%, it is recommended 
	ECHO          that this script is regenerated with the ScanWizard
)
:TESTENDED
ENDLOCAL

REM ###########################################################################
echo Starting scan
%SOURCEANALYZER% %MEMORY% %LAUNCHERSWITCHES% -b %BUILDID% -scan -f %FPR%
IF %ERRORLEVEL%==1 (
echo Sourceanalyzer failed, exiting
GOTO :FINISHED
)
REM ###########################################################################
echo Uploading scan to SSC
%CLIENT% -url %SSCURL% -authtoken %SSCTOKEN% uploadFPR -file %FPR% -project %SSCPROJECT% -version %SSCVERSION%
IF %ERRORLEVEL%==1 (
echo Sourceanalyzer failed, exiting
GOTO :FINISHED
)
REM ###########################################################################
echo Finished
:FINISHED
REM ARGS "-cp"
REM ARGS "PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\BuildConfig.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\ConfApp.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\database\Local$DbHelper.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\database\Local.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\database\quick\Bottom_Menu$1.class"
REM ARGS "-cp"
REM ARGS "PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\database\quick\Bottom_Menu$2.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\database\quick\Bottom_Menu.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\database\quick\TouchImageView$1.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\database\quick\TouchImageView$2.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\database\quick\TouchImageView$3.class"
REM ARGS "-cp"
REM ARGS "PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\database\quick\TouchImageView$ScaleListener.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\database\quick\TouchImageView.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\dataStructures\BioItem$1.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\dataStructures\BioItem.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\dataStructures\BoothLocation$Edge.class"
REM ARGS "-cp"
REM ARGS "PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\dataStructures\BoothLocation.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\dataStructures\Corner.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\dataStructures\Exhibitor.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\dataStructures\NewsItem$1.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\dataStructures\NewsItem.class"
REM ARGS "-cp"
REM ARGS "PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\dataStructures\ScheduleItem.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\dataStructures\ScheduleItem2$1.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\dataStructures\ScheduleItem2.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\dialogs\BioDetails.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\dialogs\ComboDialog$1.class"
REM ARGS "-cp"
REM ARGS "PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\dialogs\ComboDialog$2.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\dialogs\ComboDialog$3.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\dialogs\ComboDialog$4.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\dialogs\ComboDialog$5.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\dialogs\ComboDialog.class"
REM ARGS "-cp"
REM ARGS "PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\dialogs\ExhibitorList$1.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\dialogs\ExhibitorList$ExhibitorAdapter.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\dialogs\ExhibitorList.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\dialogs\NoteDetails.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\dialogs\ScheduleItemDetails.class"
REM ARGS "-cp"
REM ARGS "PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MainActivity$1.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MainActivity$InitializeAsync.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MainActivity.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MenuItems\About.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MenuItems\BoozAbout.class"
REM ARGS "-cp"
REM ARGS "PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MenuItems\Faq.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MenuItems\Favorites$1.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MenuItems\Favorites$2.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MenuItems\Favorites$ComboDialogFavorites.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MenuItems\Favorites$ScheduleAdapter$1.class"
REM ARGS "-cp"
REM ARGS "PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MenuItems\Favorites$ScheduleAdapter.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MenuItems\Favorites.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MenuItems\Future.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MenuItems\Hall.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MenuItems\Info$1.class"
REM ARGS "-cp"
REM ARGS "PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MenuItems\Info$2.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MenuItems\Info$3.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MenuItems\Info$4.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MenuItems\Info$5.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MenuItems\Info$6.class"
REM ARGS "-cp"
REM ARGS "PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MenuItems\Info$7.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MenuItems\Info.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MenuItems\Map$1.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MenuItems\Map$2.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MenuItems\Map$3.class"
REM ARGS "-cp"
REM ARGS "PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MenuItems\Map$InitializeAsync.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MenuItems\Map.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MenuItems\MenuItem.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MenuItems\MenuItems.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MenuItems\News$1.class"
REM ARGS "-cp"
REM ARGS "PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MenuItems\News$2.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MenuItems\News$InitializeAsync.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MenuItems\News$NewsAdapter$1.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MenuItems\News$NewsAdapter.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MenuItems\News$NewsAsync.class"
REM ARGS "-cp"
REM ARGS "PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MenuItems\News.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MenuItems\Notes$1.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MenuItems\Notes$2.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MenuItems\Notes$ComboDialogNotes.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MenuItems\Notes$ScheduleAdapter$1.class"
REM ARGS "-cp"
REM ARGS "PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MenuItems\Notes$ScheduleAdapter.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MenuItems\Notes.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MenuItems\Now$ScheduleAdapter$1.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MenuItems\Now$ScheduleAdapter.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MenuItems\Now.class"
REM ARGS "-cp"
REM ARGS "PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MenuItems\Schedule$1.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MenuItems\Schedule$2.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MenuItems\Schedule$3.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MenuItems\Schedule$4.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MenuItems\Schedule$ScheduleAdapter$1.class"
REM ARGS "-cp"
REM ARGS "PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MenuItems\Schedule$ScheduleAdapter.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MenuItems\Schedule$ScheduleAsync.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MenuItems\Schedule.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MenuItems\ScheduleDetails$1.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MenuItems\ScheduleDetails$2.class"
REM ARGS "-cp"
REM ARGS "PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MenuItems\ScheduleDetails.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MenuItems\Speakers$BioAdapter$1$1.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MenuItems\Speakers$BioAdapter$1.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MenuItems\Speakers$BioAdapter.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MenuItems\Speakers$InitializeAsync.class"
REM ARGS "-cp"
REM ARGS "PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MenuItems\Speakers.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MenuItems\SymposiumLocation$gaylord$1.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MenuItems\SymposiumLocation$gaylord$2.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MenuItems\SymposiumLocation$gaylord.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MenuItems\SymposiumLocation.class"
REM ARGS "-cp"
REM ARGS "PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\MenuItems\Tech.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\R$attr.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\R$color.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\R$drawable.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\R$id.class"
REM ARGS "-cp"
REM ARGS "PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\R$layout.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\R$string.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\R$style.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\R.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\web\BioParser.class"
REM ARGS "-cp"
REM ARGS "PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\web\BoothParser.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\web\ExhibitorsParser.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\web\Network.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\web\RssParser.class;PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\web\ScheduleParser.class"
REM ARGS "-cp"
REM ARGS "PROJECTROOT0_MARKER\bin\classes\bah\conference\appliation\web\ScheduleParser2.class;PROJECTROOT0_MARKER\libs\android-support-v4.jar;PROJECTROOT1_MARKER\add-ons\addon-google_apis-google-8\libs\maps.jar;PROJECTROOT1_MARKER\extras\google\analytics_sdk\libGoogleAnalytics.jar;PROJECTROOT1_MARKER\platform-tools\lib\dx.jar"
REM ARGS "-cp"
REM ARGS "PROJECTROOT1_MARKER\platforms\android-16\android.jar;PROJECTROOT1_MARKER\platforms\android-16\data\layoutlib.jar;PROJECTROOT1_MARKER\platforms\android-16\uiautomator.jar;PROJECTROOT1_MARKER\platforms\android-8\android.jar;PROJECTROOT1_MARKER\platforms\android-8\data\layoutlib.jar"
REM ARGS "-cp"
REM ARGS "PROJECTROOT1_MARKER\tools\lib\androidprefs.jar;PROJECTROOT1_MARKER\tools\lib\anttasks.jar;PROJECTROOT1_MARKER\tools\lib\archquery.jar;PROJECTROOT1_MARKER\tools\lib\asm-4.0.jar;PROJECTROOT1_MARKER\tools\lib\asm-tree-4.0.jar"
REM ARGS "-cp"
REM ARGS "PROJECTROOT1_MARKER\tools\lib\chimpchat.jar;PROJECTROOT1_MARKER\tools\lib\common.jar;PROJECTROOT1_MARKER\tools\lib\commons-codec-1.4.jar;PROJECTROOT1_MARKER\tools\lib\commons-compress-1.0.jar;PROJECTROOT1_MARKER\tools\lib\commons-logging-1.1.1.jar"
REM ARGS "-cp"
REM ARGS "PROJECTROOT1_MARKER\tools\lib\ddmlib.jar;PROJECTROOT1_MARKER\tools\lib\ddms.jar;PROJECTROOT1_MARKER\tools\lib\ddmuilib.jar;PROJECTROOT1_MARKER\tools\lib\draw9patch.jar;PROJECTROOT1_MARKER\tools\lib\dvlib.jar"
REM ARGS "-cp"
REM ARGS "PROJECTROOT1_MARKER\tools\lib\emma.jar;PROJECTROOT1_MARKER\tools\lib\emma_ant.jar;PROJECTROOT1_MARKER\tools\lib\emma_device.jar;PROJECTROOT1_MARKER\tools\lib\guava-10.0.1.jar;PROJECTROOT1_MARKER\tools\lib\guavalib.jar"
REM ARGS "-cp"
REM ARGS "PROJECTROOT1_MARKER\tools\lib\hierarchyviewer2.jar;PROJECTROOT1_MARKER\tools\lib\hierarchyviewerlib.jar;PROJECTROOT1_MARKER\tools\lib\httpclient-4.1.1.jar;PROJECTROOT1_MARKER\tools\lib\httpcore-4.1.jar;PROJECTROOT1_MARKER\tools\lib\httpmime-4.1.1.jar"
REM ARGS "-cp"
REM ARGS "PROJECTROOT1_MARKER\tools\lib\jcommon-1.0.12.jar;PROJECTROOT1_MARKER\tools\lib\jfreechart-1.0.9-swt.jar;PROJECTROOT1_MARKER\tools\lib\jfreechart-1.0.9.jar;PROJECTROOT1_MARKER\tools\lib\jsilver.jar;PROJECTROOT1_MARKER\tools\lib\jython.jar"
REM ARGS "-cp"
REM ARGS "PROJECTROOT1_MARKER\tools\lib\lint.jar;PROJECTROOT1_MARKER\tools\lib\lint_api.jar;PROJECTROOT1_MARKER\tools\lib\lint_checks.jar;PROJECTROOT1_MARKER\tools\lib\lombok-ast-0.2.jar;PROJECTROOT1_MARKER\tools\lib\manifmerger.jar"
REM ARGS "-cp"
REM ARGS "PROJECTROOT1_MARKER\tools\lib\mkidentity.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86\plugins\com.android.ide.eclipse.base_20.0.3.201208082009.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86\plugins\com.android.ide.eclipse.ddms_20.0.3.201208082009.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86\plugins\com.android.ide.eclipse.gldebugger_20.0.3.201208082009.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86\plugins\com.android.ide.eclipse.hierarchyviewer_20.0.3.201208082009.jar"
REM ARGS "-cp"
REM ARGS "PROJECTROOT1_MARKER\tools\lib\monitor-x86\plugins\com.android.ide.eclipse.monitor_20.0.3.201208082009.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86\plugins\com.android.ide.eclipse.traceview_20.0.3.201208082009.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86\plugins\com.ibm.icu_4.4.2.v20110823.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86\plugins\org.eclipse.compare.core_3.5.200.I20110208-0800.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86\plugins\org.eclipse.core.commands_3.6.0.I20110111-0800.jar"
REM ARGS "-cp"
REM ARGS "PROJECTROOT1_MARKER\tools\lib\monitor-x86\plugins\org.eclipse.core.contenttype_3.4.100.v20110423-0524.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86\plugins\org.eclipse.core.databinding.observable_1.4.0.I20110222-0800.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86\plugins\org.eclipse.core.databinding.property_1.4.0.I20110222-0800.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86\plugins\org.eclipse.core.databinding_1.4.0.I20110111-0800.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86\plugins\org.eclipse.core.expressions_3.4.300.v20110228.jar"
REM ARGS "-cp"
REM ARGS "PROJECTROOT1_MARKER\tools\lib\monitor-x86\plugins\org.eclipse.core.filesystem_1.3.100.v20110423-0524.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86\plugins\org.eclipse.core.jobs_3.5.101.v20120113-1953.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86\plugins\org.eclipse.core.resources_3.7.101.v20120125-1505.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86\plugins\org.eclipse.core.runtime.compatibility.registry_3.5.0.v20110505\runtime_registry_compatibility.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86\plugins\org.eclipse.core.runtime_3.7.0.v20110110.jar"
REM ARGS "-cp"
REM ARGS "PROJECTROOT1_MARKER\tools\lib\monitor-x86\plugins\org.eclipse.core.variables_3.2.500.v20110928-1503.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86\plugins\org.eclipse.ecf.filetransfer_5.0.0.v20110531-2218.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86\plugins\org.eclipse.ecf.identity_3.1.100.v20110531-2218.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86\plugins\org.eclipse.ecf.provider.filetransfer.ssl_1.0.0.v20110531-2218.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86\plugins\org.eclipse.ecf.provider.filetransfer_3.2.0.v20110531-2218.jar"
REM ARGS "-cp"
REM ARGS "PROJECTROOT1_MARKER\tools\lib\monitor-x86\plugins\org.eclipse.ecf.ssl_1.0.100.v20110531-2218.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86\plugins\org.eclipse.ecf_3.1.300.v20110531-2218.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86\plugins\org.eclipse.equinox.app_1.3.100.v20110321.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86\plugins\org.eclipse.equinox.common_3.6.0.v20110523.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86\plugins\org.eclipse.equinox.launcher_1.2.0.v20110502.jar"
REM ARGS "-cp"
REM ARGS "PROJECTROOT1_MARKER\tools\lib\monitor-x86\plugins\org.eclipse.equinox.p2.core_2.1.1.v20120113-1346.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86\plugins\org.eclipse.equinox.p2.engine_2.1.1.R37x_v20111003.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86\plugins\org.eclipse.equinox.p2.metadata.repository_1.2.0.v20110815-1419.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86\plugins\org.eclipse.equinox.p2.metadata_2.1.0.v20110815-1419.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86\plugins\org.eclipse.equinox.p2.repository_2.1.1.v20120113-1346.jar"
REM ARGS "-cp"
REM ARGS "PROJECTROOT1_MARKER\tools\lib\monitor-x86\plugins\org.eclipse.equinox.preferences_3.4.2.v20120111-2020.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86\plugins\org.eclipse.equinox.registry_3.5.101.R37x_v20110810-1611.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86\plugins\org.eclipse.equinox.security_1.1.1.R37x_v20110822-1018.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86\plugins\org.eclipse.help_3.5.100.v20110426.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86\plugins\org.eclipse.jface.databinding_1.5.0.I20100907-0800.jar"
REM ARGS "-cp"
REM ARGS "PROJECTROOT1_MARKER\tools\lib\monitor-x86\plugins\org.eclipse.jface.text_3.7.2.v20111213-1208.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86\plugins\org.eclipse.jface_3.7.0.v20110928-1505.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86\plugins\org.eclipse.osgi.services_3.3.0.v20110513.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86\plugins\org.eclipse.osgi_3.7.2.v20120110-1415.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86\plugins\org.eclipse.swt.win32.win32.x86_3.7.2.v3740f.jar"
REM ARGS "-cp"
REM ARGS "PROJECTROOT1_MARKER\tools\lib\monitor-x86\plugins\org.eclipse.swt_3.7.2.v3740f.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86\plugins\org.eclipse.text_3.5.101.v20110928-1504.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86\plugins\org.eclipse.ui.console_3.5.100.v20111007_r372.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86\plugins\org.eclipse.ui.ide_3.7.0.v20110928-1505.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86\plugins\org.eclipse.ui.workbench.texteditor_3.7.0.v20110928-1504.jar"
REM ARGS "-cp"
REM ARGS "PROJECTROOT1_MARKER\tools\lib\monitor-x86\plugins\org.eclipse.ui.workbench_3.7.1.v20120104-1859.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86\plugins\org.eclipse.ui_3.7.0.v20110928-1505.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86_64\plugins\com.android.ide.eclipse.base_20.0.3.201208082009.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86_64\plugins\com.android.ide.eclipse.ddms_20.0.3.201208082009.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86_64\plugins\com.android.ide.eclipse.gldebugger_20.0.3.201208082009.jar"
REM ARGS "-cp"
REM ARGS "PROJECTROOT1_MARKER\tools\lib\monitor-x86_64\plugins\com.android.ide.eclipse.hierarchyviewer_20.0.3.201208082009.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86_64\plugins\com.android.ide.eclipse.monitor_20.0.3.201208082009.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86_64\plugins\com.android.ide.eclipse.traceview_20.0.3.201208082009.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86_64\plugins\com.ibm.icu_4.4.2.v20110823.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86_64\plugins\org.eclipse.compare.core_3.5.200.I20110208-0800.jar"
REM ARGS "-cp"
REM ARGS "PROJECTROOT1_MARKER\tools\lib\monitor-x86_64\plugins\org.eclipse.core.commands_3.6.0.I20110111-0800.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86_64\plugins\org.eclipse.core.contenttype_3.4.100.v20110423-0524.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86_64\plugins\org.eclipse.core.databinding.observable_1.4.0.I20110222-0800.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86_64\plugins\org.eclipse.core.databinding.property_1.4.0.I20110222-0800.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86_64\plugins\org.eclipse.core.databinding_1.4.0.I20110111-0800.jar"
REM ARGS "-cp"
REM ARGS "PROJECTROOT1_MARKER\tools\lib\monitor-x86_64\plugins\org.eclipse.core.expressions_3.4.300.v20110228.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86_64\plugins\org.eclipse.core.filesystem_1.3.100.v20110423-0524.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86_64\plugins\org.eclipse.core.jobs_3.5.101.v20120113-1953.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86_64\plugins\org.eclipse.core.resources_3.7.101.v20120125-1505.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86_64\plugins\org.eclipse.core.runtime.compatibility.registry_3.5.0.v20110505\runtime_registry_compatibility.jar"
REM ARGS "-cp"
REM ARGS "PROJECTROOT1_MARKER\tools\lib\monitor-x86_64\plugins\org.eclipse.core.runtime_3.7.0.v20110110.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86_64\plugins\org.eclipse.core.variables_3.2.500.v20110928-1503.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86_64\plugins\org.eclipse.ecf.filetransfer_5.0.0.v20110531-2218.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86_64\plugins\org.eclipse.ecf.identity_3.1.100.v20110531-2218.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86_64\plugins\org.eclipse.ecf.provider.filetransfer.ssl_1.0.0.v20110531-2218.jar"
REM ARGS "-cp"
REM ARGS "PROJECTROOT1_MARKER\tools\lib\monitor-x86_64\plugins\org.eclipse.ecf.provider.filetransfer_3.2.0.v20110531-2218.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86_64\plugins\org.eclipse.ecf.ssl_1.0.100.v20110531-2218.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86_64\plugins\org.eclipse.ecf_3.1.300.v20110531-2218.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86_64\plugins\org.eclipse.equinox.app_1.3.100.v20110321.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86_64\plugins\org.eclipse.equinox.common_3.6.0.v20110523.jar"
REM ARGS "-cp"
REM ARGS "PROJECTROOT1_MARKER\tools\lib\monitor-x86_64\plugins\org.eclipse.equinox.launcher_1.2.0.v20110502.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86_64\plugins\org.eclipse.equinox.p2.core_2.1.1.v20120113-1346.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86_64\plugins\org.eclipse.equinox.p2.engine_2.1.1.R37x_v20111003.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86_64\plugins\org.eclipse.equinox.p2.metadata.repository_1.2.0.v20110815-1419.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86_64\plugins\org.eclipse.equinox.p2.metadata_2.1.0.v20110815-1419.jar"
REM ARGS "-cp"
REM ARGS "PROJECTROOT1_MARKER\tools\lib\monitor-x86_64\plugins\org.eclipse.equinox.p2.repository_2.1.1.v20120113-1346.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86_64\plugins\org.eclipse.equinox.preferences_3.4.2.v20120111-2020.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86_64\plugins\org.eclipse.equinox.registry_3.5.101.R37x_v20110810-1611.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86_64\plugins\org.eclipse.equinox.security_1.1.1.R37x_v20110822-1018.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86_64\plugins\org.eclipse.help_3.5.100.v20110426.jar"
REM ARGS "-cp"
REM ARGS "PROJECTROOT1_MARKER\tools\lib\monitor-x86_64\plugins\org.eclipse.jface.databinding_1.5.0.I20100907-0800.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86_64\plugins\org.eclipse.jface.text_3.7.2.v20111213-1208.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86_64\plugins\org.eclipse.jface_3.7.0.v20110928-1505.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86_64\plugins\org.eclipse.osgi.services_3.3.0.v20110513.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86_64\plugins\org.eclipse.osgi_3.7.2.v20120110-1415.jar"
REM ARGS "-cp"
REM ARGS "PROJECTROOT1_MARKER\tools\lib\monitor-x86_64\plugins\org.eclipse.swt.win32.win32.x86_64_3.7.2.v3740f.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86_64\plugins\org.eclipse.swt_3.7.2.v3740f.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86_64\plugins\org.eclipse.text_3.5.101.v20110928-1504.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86_64\plugins\org.eclipse.ui.console_3.5.100.v20111007_r372.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86_64\plugins\org.eclipse.ui.ide_3.7.0.v20110928-1505.jar"
REM ARGS "-cp"
REM ARGS "PROJECTROOT1_MARKER\tools\lib\monitor-x86_64\plugins\org.eclipse.ui.workbench.texteditor_3.7.0.v20110928-1504.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86_64\plugins\org.eclipse.ui.workbench_3.7.1.v20120104-1859.jar;PROJECTROOT1_MARKER\tools\lib\monitor-x86_64\plugins\org.eclipse.ui_3.7.0.v20110928-1505.jar;PROJECTROOT1_MARKER\tools\lib\monkeyrunner.jar;PROJECTROOT1_MARKER\tools\lib\org.eclipse.core.commands_3.6.0.I20100512-1500.jar"
REM ARGS "-cp"
REM ARGS "PROJECTROOT1_MARKER\tools\lib\org.eclipse.equinox.common_3.6.0.v20100503.jar;PROJECTROOT1_MARKER\tools\lib\org.eclipse.jface_3.6.2.M20110210-1200.jar;PROJECTROOT1_MARKER\tools\lib\osgi.jar;PROJECTROOT1_MARKER\tools\lib\sdklib.jar;PROJECTROOT1_MARKER\tools\lib\sdkmanager.jar"
REM ARGS "-cp"
REM ARGS "PROJECTROOT1_MARKER\tools\lib\sdkstats.jar;PROJECTROOT1_MARKER\tools\lib\sdkuilib.jar;PROJECTROOT1_MARKER\tools\lib\swing-worker-1.1.jar;PROJECTROOT1_MARKER\tools\lib\swtmenubar.jar;PROJECTROOT1_MARKER\tools\lib\traceview.jar"
REM ARGS "-cp"
REM ARGS "PROJECTROOT1_MARKER\tools\lib\x86\swt.jar;PROJECTROOT1_MARKER\tools\lib\x86_64\swt.jar;PROJECTROOT1_MARKER\tools\proguard\examples\annotations\lib\annotations.jar;PROJECTROOT1_MARKER\tools\proguard\lib\proguard.jar;PROJECTROOT1_MARKER\tools\proguard\lib\proguardgui.jar"
REM ARGS "-cp"
REM ARGS "PROJECTROOT1_MARKER\tools\proguard\lib\retrace.jar;PROJECTROOT1_MARKER\tools\support\annotations.jar"
REM ARGS "-source"
REM ARGS "1.6"
REM ARGS "PROJECTROOT0_MARKER"
